14,16c14
< #define VT_BOAT        (1 << 11) // Added by Lash 12-16-08
< #define VT_CONTRABAND  (1 << 12)
< 
---
> #define VT_CONTRABAND  (1 << 11)
20c18
< #define VT_ALL    VT_TREASURE | VT_WEAPON | VT_ARMOR | VT_LIGHT | VT_FOOD | VT_DRINK | VT_MAGIC | VT_FISHING | VT_PLANT | VT_HERB | VT_BOAT | VT_CONTRABAND
---
> #define VT_ALL        VT_TREASURE | VT_WEAPON | VT_ARMOR | VT_LIGHT | VT_FOOD | VT_DRINK | VT_MAGIC | VT_FISHING | VT_PLANT | VT_HERB | VT_CONTRABAND
